language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - TESTSUITE=1 COVERAGE=1 OPTS="--enable-shared"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - build@openvswitch.org
